spring:
  profiles:
    active: dev

---
server:
  port: 8051

spring:
  profiles: dev
  application:
    name: config-server-dev

---

server:
  port: 8052
spring:
  profiles: test
  application:
    name: config-server-test  
